###
POST http://localhost:7071/api/submit-basic HTTP/1.1
content-type: application/json

{
    "foregroundColor": "#ff0000",
    "backgroundColor": "#ff0000",
    "rate": 12,
    "displayName": "Bryan"
}

###
POST http://localhost:7071/api/submit-custom HTTP/1.1
content-type: application/json

{
    "functionUrl": "https://my-function-app.azurewebsites.net/api/animation",
    "displayName": "Bryan"
}

###

GET http://localhost:7071/api/get-queue HTTP/1.1
